### ISSUE TITLE
Questions in Table 1

### ISSUE THREAD

**Issue by qinliuliuqin** [LuyueShi/Hybrid-Propagation#2]
Hi, for the MSD-colon dataset, the splitting of your work is 100/26 for training/testing, while that of Mem3D is 126/64 for training/testing. How can you directly compare the two methods in Table 1? The same issue for MSD-lung.
![image](https://user-images.githubusercontent.com/57234075/219173749-930307c0-962a-4792-9c94-9bf80af5bd70.png)

**Comment by LuyueShi** [comment]
Mem3D released their codes with data split, the training set (126) of original MSD dataset was splitted for training and test, we used the same split.

**Comment by qinliuliuqin** [comment]
Hi @LuyueShi, thanks for your kind reply! The authors of the [Mem3D paper](https://www.sciencedirect.com/science/article/pii/S1361841522002316) only mentioned the official data splitting (126/64 for training/testing), and they compared their method with other methods on this official splitting (in Tab. 1 of their paper). If you rely on the data splitting file in their [codebase](https://github.com/lingorX/Mem3D/tree/main/data/MSD/ImageSets10) for your experiments, how do you split the dataset for MSD-Lung? This is not provided in their codebase.
